sudo: required
language: python

services:
  - docker
  
before_install:
- docker build -t test .
- docker run -p 8080:8080 -v `pwd`:/work test

python:
    - "3.6"
    
install: pip install requests pytest

script: pytest
